:defaults: &defaults
  :cookies:
    :secret: qwertyuiop
  :intercom:
    :app_id: f9c1fd60de50d31bcbc3f4d8d74c9c6dbc40e95a
    :api_key: <%= ENV['INTERCOM_API_KEY'] %>
  :api:
    :timeout: 5
    :ssl:
      :only_environments: production
  :swagger:
    :v1:
      :api_version: '1.0'
      :mount_path: swagger
      :hide_format: true
      :hide_documentation_path: true
      :base_path: http://localhost:9292/v1
  :redis:
    :url: redis://localhost:6379/0
    :namespace: sidekiq
  :sidekiq:
    :username: <%= ENV['SIDEKIQ_USERNAME'] %>
    :password: <%= ENV['SIDEKIQ_PASSWORD'] %>
  :amazon:
    :access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
    :secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  :amazon_mhlabs:
    :access_key_id: <%= ENV['AWS_ACCESS_KEY_MHLABS'] %>
    :secret_access_key: <%= ENV['AWS_SECRET_KEY_MHLABS'] %>
  :testserver: false
  :snapshots:
    :url: https://media.evercam.io/
    :key: <%= ENV['SNAP_KEY'] %>
    :iv: <%= ENV['SNAP_IV'] %>
  :airbrake:
     :api_key: <%= ENV['AIRBRAKE_KEY'] %>
  :streams:
    :rtmp_path: rtmp://media.evercam.io:1935
    :hls_path: https://media.evercam.io

:development:
  <<: *defaults
  :database: <%= ENV['DATABASE_URL'] %>
  :snaps_database: <%= ENV['SNAPSHOT_DATABASE_URL'] %>
  :mail:
    :from: evercam.io <support@evercam.io>
    :via: :sendmail
  :snapshots:
    :url: http://localhost:4000/
    :key: <%= ENV['SNAP_KEY'] %>
    :iv: <%= ENV['SNAP_IV'] %>
  :streams:
    :rtmp_path: rtmp://localhost:1935
    :hls_path: http://localhost:4000

:test:
  <<: *defaults
  :database: postgres://localhost/evercam_tst
  :snaps_database: postgres://localhost/evercam_tst
  :mail:
    :from: evercam.io <support@evercam.io>
    :via: :test
  :testserver: false

:production: &production
  <<: *defaults
  :database: <%= ENV['DATABASE_URL'] %>
  :snaps_database: <%= ENV['SNAPSHOT_DATABASE_URL'] %>
  :api:
    :timeout: 5
    :ssl:
      :force_secure_cookies: false
      :redirect_html: "Sorry, all API calls must be made via https. Redirecting...\n"
  :cookies:
    :secret: <%= ENV['SESSION_COOKIE_SECRET'] %>
  :swagger:
    :v1:
      :api_version: '1.0'
      :mount_path: swagger
      :hide_format: true
      :hide_documentation_path: true
      :base_path: https://api.evercam.io/v1
  :redis:
    :url: <%= ENV['REDISCLOUD_URL'] %>
    :namespace: sidekiq
  :mail:
    :from: evercam.io <support@evercam.io>
    :via: :smtp
    :via_options:
      :authentication: :plain
      :user_name: <%= ENV['SENDGRID_USERNAME'] %>
      :password: <%= ENV['SENDGRID_PASSWORD'] %>
      :enable_starttls_auto: true
      :address: 'smtp.sendgrid.net'
      :domain: 'heroku.com'
      :port: 587

:staging:
  <<: *production
  :api:
    :timeout: 5
    :ssl:
      :only_environments: production
  :cookies:
      :secret: qwertyuiop
  :mail:
    :to: env.staging@evercam.io
    :from: evercam.io <env.staging@evercam.io>
    :via: :sendmail
  :swagger:
    :v1:
      :api_version: '1.0'
      :mount_path: swagger
      :hide_format: true
      :hide_documentation_path: true
      :base_path: http://proxy.evr.cm:9292/v1
  :testserver: true

